services:
  nginx:
    image: nginx:stable
    container_name: sail_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx_sites:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/html:/etc/nginx/html:ro
    networks:
      - sailnet
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sail_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    networks:
      - sailnet
    restart: unless-stopped

networks:
  sailnet:
    name: sailnet
    driver: bridge
    external: true
